AllCops:
  TargetRubyVersion: 3.3.6
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/queue_schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - 'http:\/\/\S+'
    - 'https:\/\/\S+'

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 7

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Performance:
  Enabled: true

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: false
