default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vox_blog_development

test:
  <<: *default
  database: vox_blog_test

production:
  primary: &primary_production
    <<: *default
    database: vox_blog_production
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: vox_blog_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: vox_blog_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: vox_blog_production_cable
    migrations_paths: db/cable_migrate
